name = "cloudflare-memory-db"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# [vars]
# 可以在这里设置非敏感的环境变量
# 敏感的 API_KEY 等应该通过 wrangler secret put 设置

[[kv_namespaces]]
binding = "CACHE_KV"
id = "d237d431b2e44f0382140e0c192f4b97"

[[d1_databases]]
binding = "DB"
database_name = "memory-db-prod"
database_id = "db7dfcd2-8655-4690-a8ec-d1f9985a3b1c"
migrations_dir = "./"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "memory-vector-index"

[ai]
binding = "AI"

[vars]
APP_AUTH_TOKEN = "aRHMw1B7pFowQ0BBhlCOS6Oj8NMHGzAogMa0q0q-wS8"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "123456"
SESSION_SECRET = "cloudfMemoryDB-session-2026-05-27"
ENCRYPTION_KEY = "cloudfMemoryDB-enc-key-20260527aa"
